### ISSUE TITLE
Improve test naming convention.

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/dmsg-deprecated#16]
What do you think about renaming all variables containing `a`/`b` to something like `responder`/`initiator` or `resp`/`init`. I think it might be more readable.

_Originally posted by @nkryuchkov in https://github.com/skycoin/dmsg/pull/6/files_

**Comment by nkryuchkov** [comment]
Will be done in https://github.com/skycoin/dmsg/issues/1
